# backend:
#   name: github
#   repo: soviadmin/website
#   branch: main

backend:
  name: git-gateway
  repo: soviadmin/website
  branch: main

publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

collections:
  - name: "mardown-content"
    label: "Content"
    folder: "mardown-content"
    create: false
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
